// Code generated by go generate; DO NOT EDIT.
package multicodec

// Codec serves the purpose of type safety when passing around codecs.
type Codec uint64

// These are multicodec-packed content types.
const (
	// Identity is a codec with tag "multihash" and described by: raw binary.
	Identity Codec = 0x00 // identity
	// Cidv1 is a codec with tag "ipld" and described by: CIDv1.
	Cidv1 Codec = 0x01 // cidv1
	// Cidv2 is a codec with tag "ipld" and described by: CIDv2.
	Cidv2 Codec = 0x02 // cidv2
	// Cidv3 is a codec with tag "ipld" and described by: CIDv3.
	Cidv3 Codec = 0x03 // cidv3
	// Ip4 is a codec with tag "multiaddr".
	Ip4 Codec = 0x04 // ip4
	// Tcp is a codec with tag "multiaddr".
	Tcp Codec = 0x06 // tcp
	// Sha1 is a codec with tag "multihash".
	Sha1 Codec = 0x11 // sha1
	// Sha2_256 is a codec with tag "multihash".
	Sha2_256 Codec = 0x12 // sha2-256
	// Sha2_512 is a codec with tag "multihash".
	Sha2_512 Codec = 0x13 // sha2-512
	// Sha3_512 is a codec with tag "multihash".
	Sha3_512 Codec = 0x14 // sha3-512
	// Sha3_384 is a codec with tag "multihash".
	Sha3_384 Codec = 0x15 // sha3-384
	// Sha3_256 is a codec with tag "multihash".
	Sha3_256 Codec = 0x16 // sha3-256
	// Sha3_224 is a codec with tag "multihash".
	Sha3_224 Codec = 0x17 // sha3-224
	// Shake_128 is a codec with tag "multihash".
	Shake_128 Codec = 0x18 // shake-128
	// Shake_256 is a codec with tag "multihash".
	Shake_256 Codec = 0x19 // shake-256
	// Keccak_224 is a codec with tag "multihash" and described by: keccak has variable output length. The number specifies the core length.
	Keccak_224 Codec = 0x1a // keccak-224
	// Keccak_256 is a codec with tag "multihash".
	Keccak_256 Codec = 0x1b // keccak-256
	// Keccak_384 is a codec with tag "multihash".
	Keccak_384 Codec = 0x1c // keccak-384
	// Keccak_512 is a codec with tag "multihash".
	Keccak_512 Codec = 0x1d // keccak-512
	// Blake3 is a codec with tag "multihash" and described by: BLAKE3 has a default 32 byte output length. The maximum length is (2^64)-1 bytes..
	Blake3 Codec = 0x1e // blake3
	// Dccp is a codec with tag "multiaddr".
	Dccp Codec = 0x21 // dccp
	// Murmur3_128 is a codec with tag "multihash".
	Murmur3_128 Codec = 0x22 // murmur3-128
	// Murmur3_32 is a codec with tag "multihash".
	Murmur3_32 Codec = 0x23 // murmur3-32
	// Ip6 is a codec with tag "multiaddr".
	Ip6 Codec = 0x29 // ip6
	// Ip6zone is a codec with tag "multiaddr".
	Ip6zone Codec = 0x2a // ip6zone
	// Path is a codec with tag "namespace" and described by: Namespace for string paths. Corresponds to `/` in ASCII..
	Path Codec = 0x2f // path
	// Multicodec is a codec with tag "multiformat".
	Multicodec Codec = 0x30 // multicodec
	// Multihash is a codec with tag "multiformat".
	Multihash Codec = 0x31 // multihash
	// Multiaddr is a codec with tag "multiformat".
	Multiaddr Codec = 0x32 // multiaddr
	// Multibase is a codec with tag "multiformat".
	Multibase Codec = 0x33 // multibase
	// Dns is a codec with tag "multiaddr".
	Dns Codec = 0x35 // dns
	// Dns4 is a codec with tag "multiaddr".
	Dns4 Codec = 0x36 // dns4
	// Dns6 is a codec with tag "multiaddr".
	Dns6 Codec = 0x37 // dns6
	// Dnsaddr is a codec with tag "multiaddr".
	Dnsaddr Codec = 0x38 // dnsaddr
	// Protobuf is a codec with tag "serialization" and described by: Protocol Buffers.
	Protobuf Codec = 0x50 // protobuf
	// Cbor is a codec with tag "serialization" and described by: CBOR.
	Cbor Codec = 0x51 // cbor
	// Raw is a codec with tag "ipld" and described by: raw binary.
	Raw Codec = 0x55 // raw
	// Dbl_Sha2_256 is a codec with tag "multihash".
	Dbl_Sha2_256 Codec = 0x56 // dbl-sha2-256
	// Rlp is a codec with tag "serialization" and described by: recursive length prefix.
	Rlp Codec = 0x60 // rlp
	// Bencode is a codec with tag "serialization" and described by: bencode.
	Bencode Codec = 0x63 // bencode
	// Dag_Pb is a codec with tag "ipld" and described by: MerkleDAG protobuf.
	Dag_Pb Codec = 0x70 // dag-pb
	// Dag_Cbor is a codec with tag "ipld" and described by: MerkleDAG cbor.
	Dag_Cbor Codec = 0x71 // dag-cbor
	// Libp2p_Key is a codec with tag "ipld" and described by: Libp2p Public Key.
	Libp2p_Key Codec = 0x72 // libp2p-key
	// Git_Raw is a codec with tag "ipld" and described by: Raw Git object.
	Git_Raw Codec = 0x78 // git-raw
	// Torrent_Info is a codec with tag "ipld" and described by: Torrent file info field (bencoded).
	Torrent_Info Codec = 0x7b // torrent-info
	// Torrent_File is a codec with tag "ipld" and described by: Torrent file (bencoded).
	Torrent_File Codec = 0x7c // torrent-file
	// Leofcoin_Block is a codec with tag "ipld" and described by: Leofcoin Block.
	Leofcoin_Block Codec = 0x81 // leofcoin-block
	// Leofcoin_Tx is a codec with tag "ipld" and described by: Leofcoin Transaction.
	Leofcoin_Tx Codec = 0x82 // leofcoin-tx
	// Leofcoin_Pr is a codec with tag "ipld" and described by: Leofcoin Peer Reputation.
	Leofcoin_Pr Codec = 0x83 // leofcoin-pr
	// Sctp is a codec with tag "multiaddr".
	Sctp Codec = 0x84 // sctp
	// Dag_Jose is a codec with tag "ipld" and described by: MerkleDAG JOSE.
	Dag_Jose Codec = 0x85 // dag-jose
	// Dag_Cose is a codec with tag "ipld" and described by: MerkleDAG COSE.
	Dag_Cose Codec = 0x86 // dag-cose
	// Eth_Block is a codec with tag "ipld" and described by: Ethereum Block (RLP).
	Eth_Block Codec = 0x90 // eth-block
	// Eth_Block_List is a codec with tag "ipld" and described by: Ethereum Block List (RLP).
	Eth_Block_List Codec = 0x91 // eth-block-list
	// Eth_Tx_Trie is a codec with tag "ipld" and described by: Ethereum Transaction Trie (Eth-Trie).
	Eth_Tx_Trie Codec = 0x92 // eth-tx-trie
	// Eth_Tx is a codec with tag "ipld" and described by: Ethereum Transaction (RLP).
	Eth_Tx Codec = 0x93 // eth-tx
	// Eth_Tx_Receipt_Trie is a codec with tag "ipld" and described by: Ethereum Transaction Receipt Trie (Eth-Trie).
	Eth_Tx_Receipt_Trie Codec = 0x94 // eth-tx-receipt-trie
	// Eth_Tx_Receipt is a codec with tag "ipld" and described by: Ethereum Transaction Receipt (RLP).
	Eth_Tx_Receipt Codec = 0x95 // eth-tx-receipt
	// Eth_State_Trie is a codec with tag "ipld" and described by: Ethereum State Trie (Eth-Secure-Trie).
	Eth_State_Trie Codec = 0x96 // eth-state-trie
	// Eth_Account_Snapshot is a codec with tag "ipld" and described by: Ethereum Account Snapshot (RLP).
	Eth_Account_Snapshot Codec = 0x97 // eth-account-snapshot
	// Eth_Storage_Trie is a codec with tag "ipld" and described by: Ethereum Contract Storage Trie (Eth-Secure-Trie).
	Eth_Storage_Trie Codec = 0x98 // eth-storage-trie
	// Bitcoin_Block is a codec with tag "ipld" and described by: Bitcoin Block.
	Bitcoin_Block Codec = 0xb0 // bitcoin-block
	// Bitcoin_Tx is a codec with tag "ipld" and described by: Bitcoin Tx.
	Bitcoin_Tx Codec = 0xb1 // bitcoin-tx
	// Bitcoin_Witness_Commitment is a codec with tag "ipld" and described by: Bitcoin Witness Commitment.
	Bitcoin_Witness_Commitment Codec = 0xb2 // bitcoin-witness-commitment
	// Zcash_Block is a codec with tag "ipld" and described by: Zcash Block.
	Zcash_Block Codec = 0xc0 // zcash-block
	// Zcash_Tx is a codec with tag "ipld" and described by: Zcash Tx.
	Zcash_Tx Codec = 0xc1 // zcash-tx
	// Docid is a codec with tag "namespace" and described by: Ceramic Document Id.
	Docid Codec = 0xce // docid
	// Stellar_Block is a codec with tag "ipld" and described by: Stellar Block.
	Stellar_Block Codec = 0xd0 // stellar-block
	// Stellar_Tx is a codec with tag "ipld" and described by: Stellar Tx.
	Stellar_Tx Codec = 0xd1 // stellar-tx
	// Md4 is a codec with tag "multihash".
	Md4 Codec = 0xd4 // md4
	// Md5 is a codec with tag "multihash".
	Md5 Codec = 0xd5 // md5
	// Bmt is a codec with tag "multihash" and described by: Binary Merkle Tree Hash.
	Bmt Codec = 0xd6 // bmt
	// Decred_Block is a codec with tag "ipld" and described by: Decred Block.
	Decred_Block Codec = 0xe0 // decred-block
	// Decred_Tx is a codec with tag "ipld" and described by: Decred Tx.
	Decred_Tx Codec = 0xe1 // decred-tx
	// Ipld_Ns is a codec with tag "namespace" and described by: IPLD path.
	Ipld_Ns Codec = 0xe2 // ipld-ns
	// Ipfs_Ns is a codec with tag "namespace" and described by: IPFS path.
	Ipfs_Ns Codec = 0xe3 // ipfs-ns
	// Swarm_Ns is a codec with tag "namespace" and described by: Swarm path.
	Swarm_Ns Codec = 0xe4 // swarm-ns
	// Ipns_Ns is a codec with tag "namespace" and described by: IPNS path.
	Ipns_Ns Codec = 0xe5 // ipns-ns
	// Zeronet is a codec with tag "namespace" and described by: ZeroNet site address.
	Zeronet Codec = 0xe6 // zeronet
	// Secp256k1_Pub is a codec with tag "key" and described by: Secp256k1 public key.
	Secp256k1_Pub Codec = 0xe7 // secp256k1-pub
	// Bls12_381_G1_Pub is a codec with tag "key" and described by: BLS12-381 public key in the G1 field.
	Bls12_381_G1_Pub Codec = 0xea // bls12_381-g1-pub
	// Bls12_381_G2_Pub is a codec with tag "key" and described by: BLS12-381 public key in the G2 field.
	Bls12_381_G2_Pub Codec = 0xeb // bls12_381-g2-pub
	// X25519_Pub is a codec with tag "key" and described by: Curve25519 public key.
	X25519_Pub Codec = 0xec // x25519-pub
	// Ed25519_Pub is a codec with tag "key" and described by: Ed25519 public key.
	Ed25519_Pub Codec = 0xed // ed25519-pub
	// Bls12_381_G1g2_Pub is a codec with tag "key" and described by: BLS12-381 concatenated public keys in both the G1 and G2 fields.
	Bls12_381_G1g2_Pub Codec = 0xee // bls12_381-g1g2-pub
	// Dash_Block is a codec with tag "ipld" and described by: Dash Block.
	Dash_Block Codec = 0xf0 // dash-block
	// Dash_Tx is a codec with tag "ipld" and described by: Dash Tx.
	Dash_Tx Codec = 0xf1 // dash-tx
	// Swarm_Manifest is a codec with tag "ipld" and described by: Swarm Manifest.
	Swarm_Manifest Codec = 0xfa // swarm-manifest
	// Swarm_Feed is a codec with tag "ipld" and described by: Swarm Feed.
	Swarm_Feed Codec = 0xfb // swarm-feed
	// Udp is a codec with tag "multiaddr".
	Udp Codec = 0x0111 // udp
	// P2p_Webrtc_Star is a codec with tag "multiaddr".
	P2p_Webrtc_Star Codec = 0x0113 // p2p-webrtc-star
	// P2p_Webrtc_Direct is a codec with tag "multiaddr".
	P2p_Webrtc_Direct Codec = 0x0114 // p2p-webrtc-direct
	// P2p_Stardust is a codec with tag "multiaddr".
	P2p_Stardust Codec = 0x0115 // p2p-stardust
	// P2p_Circuit is a codec with tag "multiaddr".
	P2p_Circuit Codec = 0x0122 // p2p-circuit
	// Dag_Json is a codec with tag "ipld" and described by: MerkleDAG json.
	Dag_Json Codec = 0x0129 // dag-json
	// Udt is a codec with tag "multiaddr".
	Udt Codec = 0x012d // udt
	// Utp is a codec with tag "multiaddr".
	Utp Codec = 0x012e // utp
	// Unix is a codec with tag "multiaddr".
	Unix Codec = 0x0190 // unix
	// P2p is a codec with tag "multiaddr" and described by: libp2p.
	P2p Codec = 0x01a5 // p2p
	// Deprecated: Ipfs is a codec with tag "multiaddr" and described by: libp2p (deprecated).
	Ipfs Codec = 0x01a5 // ipfs
	// Https is a codec with tag "multiaddr".
	Https Codec = 0x01bb // https
	// Onion is a codec with tag "multiaddr".
	Onion Codec = 0x01bc // onion
	// Onion3 is a codec with tag "multiaddr".
	Onion3 Codec = 0x01bd // onion3
	// Garlic64 is a codec with tag "multiaddr" and described by: I2P base64 (raw public key).
	Garlic64 Codec = 0x01be // garlic64
	// Garlic32 is a codec with tag "multiaddr" and described by: I2P base32 (hashed public key or encoded public key/checksum+optional secret).
	Garlic32 Codec = 0x01bf // garlic32
	// Tls is a codec with tag "multiaddr".
	Tls Codec = 0x01c0 // tls
	// Quic is a codec with tag "multiaddr".
	Quic Codec = 0x01cc // quic
	// Ws is a codec with tag "multiaddr".
	Ws Codec = 0x01dd // ws
	// Wss is a codec with tag "multiaddr".
	Wss Codec = 0x01de // wss
	// P2p_Websocket_Star is a codec with tag "multiaddr".
	P2p_Websocket_Star Codec = 0x01df // p2p-websocket-star
	// Http is a codec with tag "multiaddr".
	Http Codec = 0x01e0 // http
	// Json is a codec with tag "serialization" and described by: JSON (UTF-8-encoded).
	Json Codec = 0x0200 // json
	// Messagepack is a codec with tag "serialization" and described by: MessagePack.
	Messagepack Codec = 0x0201 // messagepack
	// Libp2p_Peer_Record is a codec with tag "libp2p" and described by: libp2p peer record type.
	Libp2p_Peer_Record Codec = 0x0301 // libp2p-peer-record
	// Sha2_256_Trunc254_Padded is a codec with tag "multihash" and described by: SHA2-256 with the two most significant bits from the last byte zeroed (as via a mask with 0b00111111) - used for proving trees as in Filecoin.
	Sha2_256_Trunc254_Padded Codec = 0x1012 // sha2-256-trunc254-padded
	// Ripemd_128 is a codec with tag "multihash".
	Ripemd_128 Codec = 0x1052 // ripemd-128
	// Ripemd_160 is a codec with tag "multihash".
	Ripemd_160 Codec = 0x1053 // ripemd-160
	// Ripemd_256 is a codec with tag "multihash".
	Ripemd_256 Codec = 0x1054 // ripemd-256
	// Ripemd_320 is a codec with tag "multihash".
	Ripemd_320 Codec = 0x1055 // ripemd-320
	// X11 is a codec with tag "multihash".
	X11 Codec = 0x1100 // x11
	// P256_Pub is a codec with tag "key" and described by: P-256 public Key.
	P256_Pub Codec = 0x1200 // p256-pub
	// P384_Pub is a codec with tag "key" and described by: P-384 public Key.
	P384_Pub Codec = 0x1201 // p384-pub
	// P521_Pub is a codec with tag "key" and described by: P-521 public Key.
	P521_Pub Codec = 0x1202 // p521-pub
	// Ed448_Pub is a codec with tag "key" and described by: Ed448 public Key.
	Ed448_Pub Codec = 0x1203 // ed448-pub
	// X448_Pub is a codec with tag "key" and described by: X448 public Key.
	X448_Pub Codec = 0x1204 // x448-pub
	// Ed25519_Priv is a codec with tag "key" and described by: Ed25519 private key.
	Ed25519_Priv Codec = 0x1300 // ed25519-priv
	// Kangarootwelve is a codec with tag "multihash" and described by: KangarooTwelve is an extendable-output hash function based on Keccak-p.
	Kangarootwelve Codec = 0x1d01 // kangarootwelve
	// Sm3_256 is a codec with tag "multihash".
	Sm3_256 Codec = 0x534d // sm3-256
	// Blake2b_8 is a codec with tag "multihash" and described by: Blake2b consists of 64 output lengths that give different hashes.
	Blake2b_8 Codec = 0xb201 // blake2b-8
	// Blake2b_16 is a codec with tag "multihash".
	Blake2b_16 Codec = 0xb202 // blake2b-16
	// Blake2b_24 is a codec with tag "multihash".
	Blake2b_24 Codec = 0xb203 // blake2b-24
	// Blake2b_32 is a codec with tag "multihash".
	Blake2b_32 Codec = 0xb204 // blake2b-32
	// Blake2b_40 is a codec with tag "multihash".
	Blake2b_40 Codec = 0xb205 // blake2b-40
	// Blake2b_48 is a codec with tag "multihash".
	Blake2b_48 Codec = 0xb206 // blake2b-48
	// Blake2b_56 is a codec with tag "multihash".
	Blake2b_56 Codec = 0xb207 // blake2b-56
	// Blake2b_64 is a codec with tag "multihash".
	Blake2b_64 Codec = 0xb208 // blake2b-64
	// Blake2b_72 is a codec with tag "multihash".
	Blake2b_72 Codec = 0xb209 // blake2b-72
	// Blake2b_80 is a codec with tag "multihash".
	Blake2b_80 Codec = 0xb20a // blake2b-80
	// Blake2b_88 is a codec with tag "multihash".
	Blake2b_88 Codec = 0xb20b // blake2b-88
	// Blake2b_96 is a codec with tag "multihash".
	Blake2b_96 Codec = 0xb20c // blake2b-96
	// Blake2b_104 is a codec with tag "multihash".
	Blake2b_104 Codec = 0xb20d // blake2b-104
	// Blake2b_112 is a codec with tag "multihash".
	Blake2b_112 Codec = 0xb20e // blake2b-112
	// Blake2b_120 is a codec with tag "multihash".
	Blake2b_120 Codec = 0xb20f // blake2b-120
	// Blake2b_128 is a codec with tag "multihash".
	Blake2b_128 Codec = 0xb210 // blake2b-128
	// Blake2b_136 is a codec with tag "multihash".
	Blake2b_136 Codec = 0xb211 // blake2b-136
	// Blake2b_144 is a codec with tag "multihash".
	Blake2b_144 Codec = 0xb212 // blake2b-144
	// Blake2b_152 is a codec with tag "multihash".
	Blake2b_152 Codec = 0xb213 // blake2b-152
	// Blake2b_160 is a codec with tag "multihash".
	Blake2b_160 Codec = 0xb214 // blake2b-160
	// Blake2b_168 is a codec with tag "multihash".
	Blake2b_168 Codec = 0xb215 // blake2b-168
	// Blake2b_176 is a codec with tag "multihash".
	Blake2b_176 Codec = 0xb216 // blake2b-176
	// Blake2b_184 is a codec with tag "multihash".
	Blake2b_184 Codec = 0xb217 // blake2b-184
	// Blake2b_192 is a codec with tag "multihash".
	Blake2b_192 Codec = 0xb218 // blake2b-192
	// Blake2b_200 is a codec with tag "multihash".
	Blake2b_200 Codec = 0xb219 // blake2b-200
	// Blake2b_208 is a codec with tag "multihash".
	Blake2b_208 Codec = 0xb21a // blake2b-208
	// Blake2b_216 is a codec with tag "multihash".
	Blake2b_216 Codec = 0xb21b // blake2b-216
	// Blake2b_224 is a codec with tag "multihash".
	Blake2b_224 Codec = 0xb21c // blake2b-224
	// Blake2b_232 is a codec with tag "multihash".
	Blake2b_232 Codec = 0xb21d // blake2b-232
	// Blake2b_240 is a codec with tag "multihash".
	Blake2b_240 Codec = 0xb21e // blake2b-240
	// Blake2b_248 is a codec with tag "multihash".
	Blake2b_248 Codec = 0xb21f // blake2b-248
	// Blake2b_256 is a codec with tag "multihash".
	Blake2b_256 Codec = 0xb220 // blake2b-256
	// Blake2b_264 is a codec with tag "multihash".
	Blake2b_264 Codec = 0xb221 // blake2b-264
	// Blake2b_272 is a codec with tag "multihash".
	Blake2b_272 Codec = 0xb222 // blake2b-272
	// Blake2b_280 is a codec with tag "multihash".
	Blake2b_280 Codec = 0xb223 // blake2b-280
	// Blake2b_288 is a codec with tag "multihash".
	Blake2b_288 Codec = 0xb224 // blake2b-288
	// Blake2b_296 is a codec with tag "multihash".
	Blake2b_296 Codec = 0xb225 // blake2b-296
	// Blake2b_304 is a codec with tag "multihash".
	Blake2b_304 Codec = 0xb226 // blake2b-304
	// Blake2b_312 is a codec with tag "multihash".
	Blake2b_312 Codec = 0xb227 // blake2b-312
	// Blake2b_320 is a codec with tag "multihash".
	Blake2b_320 Codec = 0xb228 // blake2b-320
	// Blake2b_328 is a codec with tag "multihash".
	Blake2b_328 Codec = 0xb229 // blake2b-328
	// Blake2b_336 is a codec with tag "multihash".
	Blake2b_336 Codec = 0xb22a // blake2b-336
	// Blake2b_344 is a codec with tag "multihash".
	Blake2b_344 Codec = 0xb22b // blake2b-344
	// Blake2b_352 is a codec with tag "multihash".
	Blake2b_352 Codec = 0xb22c // blake2b-352
	// Blake2b_360 is a codec with tag "multihash".
	Blake2b_360 Codec = 0xb22d // blake2b-360
	// Blake2b_368 is a codec with tag "multihash".
	Blake2b_368 Codec = 0xb22e // blake2b-368
	// Blake2b_376 is a codec with tag "multihash".
	Blake2b_376 Codec = 0xb22f // blake2b-376
	// Blake2b_384 is a codec with tag "multihash".
	Blake2b_384 Codec = 0xb230 // blake2b-384
	// Blake2b_392 is a codec with tag "multihash".
	Blake2b_392 Codec = 0xb231 // blake2b-392
	// Blake2b_400 is a codec with tag "multihash".
	Blake2b_400 Codec = 0xb232 // blake2b-400
	// Blake2b_408 is a codec with tag "multihash".
	Blake2b_408 Codec = 0xb233 // blake2b-408
	// Blake2b_416 is a codec with tag "multihash".
	Blake2b_416 Codec = 0xb234 // blake2b-416
	// Blake2b_424 is a codec with tag "multihash".
	Blake2b_424 Codec = 0xb235 // blake2b-424
	// Blake2b_432 is a codec with tag "multihash".
	Blake2b_432 Codec = 0xb236 // blake2b-432
	// Blake2b_440 is a codec with tag "multihash".
	Blake2b_440 Codec = 0xb237 // blake2b-440
	// Blake2b_448 is a codec with tag "multihash".
	Blake2b_448 Codec = 0xb238 // blake2b-448
	// Blake2b_456 is a codec with tag "multihash".
	Blake2b_456 Codec = 0xb239 // blake2b-456
	// Blake2b_464 is a codec with tag "multihash".
	Blake2b_464 Codec = 0xb23a // blake2b-464
	// Blake2b_472 is a codec with tag "multihash".
	Blake2b_472 Codec = 0xb23b // blake2b-472
	// Blake2b_480 is a codec with tag "multihash".
	Blake2b_480 Codec = 0xb23c // blake2b-480
	// Blake2b_488 is a codec with tag "multihash".
	Blake2b_488 Codec = 0xb23d // blake2b-488
	// Blake2b_496 is a codec with tag "multihash".
	Blake2b_496 Codec = 0xb23e // blake2b-496
	// Blake2b_504 is a codec with tag "multihash".
	Blake2b_504 Codec = 0xb23f // blake2b-504
	// Blake2b_512 is a codec with tag "multihash".
	Blake2b_512 Codec = 0xb240 // blake2b-512
	// Blake2s_8 is a codec with tag "multihash" and described by: Blake2s consists of 32 output lengths that give different hashes.
	Blake2s_8 Codec = 0xb241 // blake2s-8
	// Blake2s_16 is a codec with tag "multihash".
	Blake2s_16 Codec = 0xb242 // blake2s-16
	// Blake2s_24 is a codec with tag "multihash".
	Blake2s_24 Codec = 0xb243 // blake2s-24
	// Blake2s_32 is a codec with tag "multihash".
	Blake2s_32 Codec = 0xb244 // blake2s-32
	// Blake2s_40 is a codec with tag "multihash".
	Blake2s_40 Codec = 0xb245 // blake2s-40
	// Blake2s_48 is a codec with tag "multihash".
	Blake2s_48 Codec = 0xb246 // blake2s-48
	// Blake2s_56 is a codec with tag "multihash".
	Blake2s_56 Codec = 0xb247 // blake2s-56
	// Blake2s_64 is a codec with tag "multihash".
	Blake2s_64 Codec = 0xb248 // blake2s-64
	// Blake2s_72 is a codec with tag "multihash".
	Blake2s_72 Codec = 0xb249 // blake2s-72
	// Blake2s_80 is a codec with tag "multihash".
	Blake2s_80 Codec = 0xb24a // blake2s-80
	// Blake2s_88 is a codec with tag "multihash".
	Blake2s_88 Codec = 0xb24b // blake2s-88
	// Blake2s_96 is a codec with tag "multihash".
	Blake2s_96 Codec = 0xb24c // blake2s-96
	// Blake2s_104 is a codec with tag "multihash".
	Blake2s_104 Codec = 0xb24d // blake2s-104
	// Blake2s_112 is a codec with tag "multihash".
	Blake2s_112 Codec = 0xb24e // blake2s-112
	// Blake2s_120 is a codec with tag "multihash".
	Blake2s_120 Codec = 0xb24f // blake2s-120
	// Blake2s_128 is a codec with tag "multihash".
	Blake2s_128 Codec = 0xb250 // blake2s-128
	// Blake2s_136 is a codec with tag "multihash".
	Blake2s_136 Codec = 0xb251 // blake2s-136
	// Blake2s_144 is a codec with tag "multihash".
	Blake2s_144 Codec = 0xb252 // blake2s-144
	// Blake2s_152 is a codec with tag "multihash".
	Blake2s_152 Codec = 0xb253 // blake2s-152
	// Blake2s_160 is a codec with tag "multihash".
	Blake2s_160 Codec = 0xb254 // blake2s-160
	// Blake2s_168 is a codec with tag "multihash".
	Blake2s_168 Codec = 0xb255 // blake2s-168
	// Blake2s_176 is a codec with tag "multihash".
	Blake2s_176 Codec = 0xb256 // blake2s-176
	// Blake2s_184 is a codec with tag "multihash".
	Blake2s_184 Codec = 0xb257 // blake2s-184
	// Blake2s_192 is a codec with tag "multihash".
	Blake2s_192 Codec = 0xb258 // blake2s-192
	// Blake2s_200 is a codec with tag "multihash".
	Blake2s_200 Codec = 0xb259 // blake2s-200
	// Blake2s_208 is a codec with tag "multihash".
	Blake2s_208 Codec = 0xb25a // blake2s-208
	// Blake2s_216 is a codec with tag "multihash".
	Blake2s_216 Codec = 0xb25b // blake2s-216
	// Blake2s_224 is a codec with tag "multihash".
	Blake2s_224 Codec = 0xb25c // blake2s-224
	// Blake2s_232 is a codec with tag "multihash".
	Blake2s_232 Codec = 0xb25d // blake2s-232
	// Blake2s_240 is a codec with tag "multihash".
	Blake2s_240 Codec = 0xb25e // blake2s-240
	// Blake2s_248 is a codec with tag "multihash".
	Blake2s_248 Codec = 0xb25f // blake2s-248
	// Blake2s_256 is a codec with tag "multihash".
	Blake2s_256 Codec = 0xb260 // blake2s-256
	// Skein256_8 is a codec with tag "multihash" and described by: Skein256 consists of 32 output lengths that give different hashes.
	Skein256_8 Codec = 0xb301 // skein256-8
	// Skein256_16 is a codec with tag "multihash".
	Skein256_16 Codec = 0xb302 // skein256-16
	// Skein256_24 is a codec with tag "multihash".
	Skein256_24 Codec = 0xb303 // skein256-24
	// Skein256_32 is a codec with tag "multihash".
	Skein256_32 Codec = 0xb304 // skein256-32
	// Skein256_40 is a codec with tag "multihash".
	Skein256_40 Codec = 0xb305 // skein256-40
	// Skein256_48 is a codec with tag "multihash".
	Skein256_48 Codec = 0xb306 // skein256-48
	// Skein256_56 is a codec with tag "multihash".
	Skein256_56 Codec = 0xb307 // skein256-56
	// Skein256_64 is a codec with tag "multihash".
	Skein256_64 Codec = 0xb308 // skein256-64
	// Skein256_72 is a codec with tag "multihash".
	Skein256_72 Codec = 0xb309 // skein256-72
	// Skein256_80 is a codec with tag "multihash".
	Skein256_80 Codec = 0xb30a // skein256-80
	// Skein256_88 is a codec with tag "multihash".
	Skein256_88 Codec = 0xb30b // skein256-88
	// Skein256_96 is a codec with tag "multihash".
	Skein256_96 Codec = 0xb30c // skein256-96
	// Skein256_104 is a codec with tag "multihash".
	Skein256_104 Codec = 0xb30d // skein256-104
	// Skein256_112 is a codec with tag "multihash".
	Skein256_112 Codec = 0xb30e // skein256-112
	// Skein256_120 is a codec with tag "multihash".
	Skein256_120 Codec = 0xb30f // skein256-120
	// Skein256_128 is a codec with tag "multihash".
	Skein256_128 Codec = 0xb310 // skein256-128
	// Skein256_136 is a codec with tag "multihash".
	Skein256_136 Codec = 0xb311 // skein256-136
	// Skein256_144 is a codec with tag "multihash".
	Skein256_144 Codec = 0xb312 // skein256-144
	// Skein256_152 is a codec with tag "multihash".
	Skein256_152 Codec = 0xb313 // skein256-152
	// Skein256_160 is a codec with tag "multihash".
	Skein256_160 Codec = 0xb314 // skein256-160
	// Skein256_168 is a codec with tag "multihash".
	Skein256_168 Codec = 0xb315 // skein256-168
	// Skein256_176 is a codec with tag "multihash".
	Skein256_176 Codec = 0xb316 // skein256-176
	// Skein256_184 is a codec with tag "multihash".
	Skein256_184 Codec = 0xb317 // skein256-184
	// Skein256_192 is a codec with tag "multihash".
	Skein256_192 Codec = 0xb318 // skein256-192
	// Skein256_200 is a codec with tag "multihash".
	Skein256_200 Codec = 0xb319 // skein256-200
	// Skein256_208 is a codec with tag "multihash".
	Skein256_208 Codec = 0xb31a // skein256-208
	// Skein256_216 is a codec with tag "multihash".
	Skein256_216 Codec = 0xb31b // skein256-216
	// Skein256_224 is a codec with tag "multihash".
	Skein256_224 Codec = 0xb31c // skein256-224
	// Skein256_232 is a codec with tag "multihash".
	Skein256_232 Codec = 0xb31d // skein256-232
	// Skein256_240 is a codec with tag "multihash".
	Skein256_240 Codec = 0xb31e // skein256-240
	// Skein256_248 is a codec with tag "multihash".
	Skein256_248 Codec = 0xb31f // skein256-248
	// Skein256_256 is a codec with tag "multihash".
	Skein256_256 Codec = 0xb320 // skein256-256
	// Skein512_8 is a codec with tag "multihash" and described by: Skein512 consists of 64 output lengths that give different hashes.
	Skein512_8 Codec = 0xb321 // skein512-8
	// Skein512_16 is a codec with tag "multihash".
	Skein512_16 Codec = 0xb322 // skein512-16
	// Skein512_24 is a codec with tag "multihash".
	Skein512_24 Codec = 0xb323 // skein512-24
	// Skein512_32 is a codec with tag "multihash".
	Skein512_32 Codec = 0xb324 // skein512-32
	// Skein512_40 is a codec with tag "multihash".
	Skein512_40 Codec = 0xb325 // skein512-40
	// Skein512_48 is a codec with tag "multihash".
	Skein512_48 Codec = 0xb326 // skein512-48
	// Skein512_56 is a codec with tag "multihash".
	Skein512_56 Codec = 0xb327 // skein512-56
	// Skein512_64 is a codec with tag "multihash".
	Skein512_64 Codec = 0xb328 // skein512-64
	// Skein512_72 is a codec with tag "multihash".
	Skein512_72 Codec = 0xb329 // skein512-72
	// Skein512_80 is a codec with tag "multihash".
	Skein512_80 Codec = 0xb32a // skein512-80
	// Skein512_88 is a codec with tag "multihash".
	Skein512_88 Codec = 0xb32b // skein512-88
	// Skein512_96 is a codec with tag "multihash".
	Skein512_96 Codec = 0xb32c // skein512-96
	// Skein512_104 is a codec with tag "multihash".
	Skein512_104 Codec = 0xb32d // skein512-104
	// Skein512_112 is a codec with tag "multihash".
	Skein512_112 Codec = 0xb32e // skein512-112
	// Skein512_120 is a codec with tag "multihash".
	Skein512_120 Codec = 0xb32f // skein512-120
	// Skein512_128 is a codec with tag "multihash".
	Skein512_128 Codec = 0xb330 // skein512-128
	// Skein512_136 is a codec with tag "multihash".
	Skein512_136 Codec = 0xb331 // skein512-136
	// Skein512_144 is a codec with tag "multihash".
	Skein512_144 Codec = 0xb332 // skein512-144
	// Skein512_152 is a codec with tag "multihash".
	Skein512_152 Codec = 0xb333 // skein512-152
	// Skein512_160 is a codec with tag "multihash".
	Skein512_160 Codec = 0xb334 // skein512-160
	// Skein512_168 is a codec with tag "multihash".
	Skein512_168 Codec = 0xb335 // skein512-168
	// Skein512_176 is a codec with tag "multihash".
	Skein512_176 Codec = 0xb336 // skein512-176
	// Skein512_184 is a codec with tag "multihash".
	Skein512_184 Codec = 0xb337 // skein512-184
	// Skein512_192 is a codec with tag "multihash".
	Skein512_192 Codec = 0xb338 // skein512-192
	// Skein512_200 is a codec with tag "multihash".
	Skein512_200 Codec = 0xb339 // skein512-200
	// Skein512_208 is a codec with tag "multihash".
	Skein512_208 Codec = 0xb33a // skein512-208
	// Skein512_216 is a codec with tag "multihash".
	Skein512_216 Codec = 0xb33b // skein512-216
	// Skein512_224 is a codec with tag "multihash".
	Skein512_224 Codec = 0xb33c // skein512-224
	// Skein512_232 is a codec with tag "multihash".
	Skein512_232 Codec = 0xb33d // skein512-232
	// Skein512_240 is a codec with tag "multihash".
	Skein512_240 Codec = 0xb33e // skein512-240
	// Skein512_248 is a codec with tag "multihash".
	Skein512_248 Codec = 0xb33f // skein512-248
	// Skein512_256 is a codec with tag "multihash".
	Skein512_256 Codec = 0xb340 // skein512-256
	// Skein512_264 is a codec with tag "multihash".
	Skein512_264 Codec = 0xb341 // skein512-264
	// Skein512_272 is a codec with tag "multihash".
	Skein512_272 Codec = 0xb342 // skein512-272
	// Skein512_280 is a codec with tag "multihash".
	Skein512_280 Codec = 0xb343 // skein512-280
	// Skein512_288 is a codec with tag "multihash".
	Skein512_288 Codec = 0xb344 // skein512-288
	// Skein512_296 is a codec with tag "multihash".
	Skein512_296 Codec = 0xb345 // skein512-296
	// Skein512_304 is a codec with tag "multihash".
	Skein512_304 Codec = 0xb346 // skein512-304
	// Skein512_312 is a codec with tag "multihash".
	Skein512_312 Codec = 0xb347 // skein512-312
	// Skein512_320 is a codec with tag "multihash".
	Skein512_320 Codec = 0xb348 // skein512-320
	// Skein512_328 is a codec with tag "multihash".
	Skein512_328 Codec = 0xb349 // skein512-328
	// Skein512_336 is a codec with tag "multihash".
	Skein512_336 Codec = 0xb34a // skein512-336
	// Skein512_344 is a codec with tag "multihash".
	Skein512_344 Codec = 0xb34b // skein512-344
	// Skein512_352 is a codec with tag "multihash".
	Skein512_352 Codec = 0xb34c // skein512-352
	// Skein512_360 is a codec with tag "multihash".
	Skein512_360 Codec = 0xb34d // skein512-360
	// Skein512_368 is a codec with tag "multihash".
	Skein512_368 Codec = 0xb34e // skein512-368
	// Skein512_376 is a codec with tag "multihash".
	Skein512_376 Codec = 0xb34f // skein512-376
	// Skein512_384 is a codec with tag "multihash".
	Skein512_384 Codec = 0xb350 // skein512-384
	// Skein512_392 is a codec with tag "multihash".
	Skein512_392 Codec = 0xb351 // skein512-392
	// Skein512_400 is a codec with tag "multihash".
	Skein512_400 Codec = 0xb352 // skein512-400
	// Skein512_408 is a codec with tag "multihash".
	Skein512_408 Codec = 0xb353 // skein512-408
	// Skein512_416 is a codec with tag "multihash".
	Skein512_416 Codec = 0xb354 // skein512-416
	// Skein512_424 is a codec with tag "multihash".
	Skein512_424 Codec = 0xb355 // skein512-424
	// Skein512_432 is a codec with tag "multihash".
	Skein512_432 Codec = 0xb356 // skein512-432
	// Skein512_440 is a codec with tag "multihash".
	Skein512_440 Codec = 0xb357 // skein512-440
	// Skein512_448 is a codec with tag "multihash".
	Skein512_448 Codec = 0xb358 // skein512-448
	// Skein512_456 is a codec with tag "multihash".
	Skein512_456 Codec = 0xb359 // skein512-456
	// Skein512_464 is a codec with tag "multihash".
	Skein512_464 Codec = 0xb35a // skein512-464
	// Skein512_472 is a codec with tag "multihash".
	Skein512_472 Codec = 0xb35b // skein512-472
	// Skein512_480 is a codec with tag "multihash".
	Skein512_480 Codec = 0xb35c // skein512-480
	// Skein512_488 is a codec with tag "multihash".
	Skein512_488 Codec = 0xb35d // skein512-488
	// Skein512_496 is a codec with tag "multihash".
	Skein512_496 Codec = 0xb35e // skein512-496
	// Skein512_504 is a codec with tag "multihash".
	Skein512_504 Codec = 0xb35f // skein512-504
	// Skein512_512 is a codec with tag "multihash".
	Skein512_512 Codec = 0xb360 // skein512-512
	// Skein1024_8 is a codec with tag "multihash" and described by: Skein1024 consists of 128 output lengths that give different hashes.
	Skein1024_8 Codec = 0xb361 // skein1024-8
	// Skein1024_16 is a codec with tag "multihash".
	Skein1024_16 Codec = 0xb362 // skein1024-16
	// Skein1024_24 is a codec with tag "multihash".
	Skein1024_24 Codec = 0xb363 // skein1024-24
	// Skein1024_32 is a codec with tag "multihash".
	Skein1024_32 Codec = 0xb364 // skein1024-32
	// Skein1024_40 is a codec with tag "multihash".
	Skein1024_40 Codec = 0xb365 // skein1024-40
	// Skein1024_48 is a codec with tag "multihash".
	Skein1024_48 Codec = 0xb366 // skein1024-48
	// Skein1024_56 is a codec with tag "multihash".
	Skein1024_56 Codec = 0xb367 // skein1024-56
	// Skein1024_64 is a codec with tag "multihash".
	Skein1024_64 Codec = 0xb368 // skein1024-64
	// Skein1024_72 is a codec with tag "multihash".
	Skein1024_72 Codec = 0xb369 // skein1024-72
	// Skein1024_80 is a codec with tag "multihash".
	Skein1024_80 Codec = 0xb36a // skein1024-80
	// Skein1024_88 is a codec with tag "multihash".
	Skein1024_88 Codec = 0xb36b // skein1024-88
	// Skein1024_96 is a codec with tag "multihash".
	Skein1024_96 Codec = 0xb36c // skein1024-96
	// Skein1024_104 is a codec with tag "multihash".
	Skein1024_104 Codec = 0xb36d // skein1024-104
	// Skein1024_112 is a codec with tag "multihash".
	Skein1024_112 Codec = 0xb36e // skein1024-112
	// Skein1024_120 is a codec with tag "multihash".
	Skein1024_120 Codec = 0xb36f // skein1024-120
	// Skein1024_128 is a codec with tag "multihash".
	Skein1024_128 Codec = 0xb370 // skein1024-128
	// Skein1024_136 is a codec with tag "multihash".
	Skein1024_136 Codec = 0xb371 // skein1024-136
	// Skein1024_144 is a codec with tag "multihash".
	Skein1024_144 Codec = 0xb372 // skein1024-144
	// Skein1024_152 is a codec with tag "multihash".
	Skein1024_152 Codec = 0xb373 // skein1024-152
	// Skein1024_160 is a codec with tag "multihash".
	Skein1024_160 Codec = 0xb374 // skein1024-160
	// Skein1024_168 is a codec with tag "multihash".
	Skein1024_168 Codec = 0xb375 // skein1024-168
	// Skein1024_176 is a codec with tag "multihash".
	Skein1024_176 Codec = 0xb376 // skein1024-176
	// Skein1024_184 is a codec with tag "multihash".
	Skein1024_184 Codec = 0xb377 // skein1024-184
	// Skein1024_192 is a codec with tag "multihash".
	Skein1024_192 Codec = 0xb378 // skein1024-192
	// Skein1024_200 is a codec with tag "multihash".
	Skein1024_200 Codec = 0xb379 // skein1024-200
	// Skein1024_208 is a codec with tag "multihash".
	Skein1024_208 Codec = 0xb37a // skein1024-208
	// Skein1024_216 is a codec with tag "multihash".
	Skein1024_216 Codec = 0xb37b // skein1024-216
	// Skein1024_224 is a codec with tag "multihash".
	Skein1024_224 Codec = 0xb37c // skein1024-224
	// Skein1024_232 is a codec with tag "multihash".
	Skein1024_232 Codec = 0xb37d // skein1024-232
	// Skein1024_240 is a codec with tag "multihash".
	Skein1024_240 Codec = 0xb37e // skein1024-240
	// Skein1024_248 is a codec with tag "multihash".
	Skein1024_248 Codec = 0xb37f // skein1024-248
	// Skein1024_256 is a codec with tag "multihash".
	Skein1024_256 Codec = 0xb380 // skein1024-256
	// Skein1024_264 is a codec with tag "multihash".
	Skein1024_264 Codec = 0xb381 // skein1024-264
	// Skein1024_272 is a codec with tag "multihash".
	Skein1024_272 Codec = 0xb382 // skein1024-272
	// Skein1024_280 is a codec with tag "multihash".
	Skein1024_280 Codec = 0xb383 // skein1024-280
	// Skein1024_288 is a codec with tag "multihash".
	Skein1024_288 Codec = 0xb384 // skein1024-288
	// Skein1024_296 is a codec with tag "multihash".
	Skein1024_296 Codec = 0xb385 // skein1024-296
	// Skein1024_304 is a codec with tag "multihash".
	Skein1024_304 Codec = 0xb386 // skein1024-304
	// Skein1024_312 is a codec with tag "multihash".
	Skein1024_312 Codec = 0xb387 // skein1024-312
	// Skein1024_320 is a codec with tag "multihash".
	Skein1024_320 Codec = 0xb388 // skein1024-320
	// Skein1024_328 is a codec with tag "multihash".
	Skein1024_328 Codec = 0xb389 // skein1024-328
	// Skein1024_336 is a codec with tag "multihash".
	Skein1024_336 Codec = 0xb38a // skein1024-336
	// Skein1024_344 is a codec with tag "multihash".
	Skein1024_344 Codec = 0xb38b // skein1024-344
	// Skein1024_352 is a codec with tag "multihash".
	Skein1024_352 Codec = 0xb38c // skein1024-352
	// Skein1024_360 is a codec with tag "multihash".
	Skein1024_360 Codec = 0xb38d // skein1024-360
	// Skein1024_368 is a codec with tag "multihash".
	Skein1024_368 Codec = 0xb38e // skein1024-368
	// Skein1024_376 is a codec with tag "multihash".
	Skein1024_376 Codec = 0xb38f // skein1024-376
	// Skein1024_384 is a codec with tag "multihash".
	Skein1024_384 Codec = 0xb390 // skein1024-384
	// Skein1024_392 is a codec with tag "multihash".
	Skein1024_392 Codec = 0xb391 // skein1024-392
	// Skein1024_400 is a codec with tag "multihash".
	Skein1024_400 Codec = 0xb392 // skein1024-400
	// Skein1024_408 is a codec with tag "multihash".
	Skein1024_408 Codec = 0xb393 // skein1024-408
	// Skein1024_416 is a codec with tag "multihash".
	Skein1024_416 Codec = 0xb394 // skein1024-416
	// Skein1024_424 is a codec with tag "multihash".
	Skein1024_424 Codec = 0xb395 // skein1024-424
	// Skein1024_432 is a codec with tag "multihash".
	Skein1024_432 Codec = 0xb396 // skein1024-432
	// Skein1024_440 is a codec with tag "multihash".
	Skein1024_440 Codec = 0xb397 // skein1024-440
	// Skein1024_448 is a codec with tag "multihash".
	Skein1024_448 Codec = 0xb398 // skein1024-448
	// Skein1024_456 is a codec with tag "multihash".
	Skein1024_456 Codec = 0xb399 // skein1024-456
	// Skein1024_464 is a codec with tag "multihash".
	Skein1024_464 Codec = 0xb39a // skein1024-464
	// Skein1024_472 is a codec with tag "multihash".
	Skein1024_472 Codec = 0xb39b // skein1024-472
	// Skein1024_480 is a codec with tag "multihash".
	Skein1024_480 Codec = 0xb39c // skein1024-480
	// Skein1024_488 is a codec with tag "multihash".
	Skein1024_488 Codec = 0xb39d // skein1024-488
	// Skein1024_496 is a codec with tag "multihash".
	Skein1024_496 Codec = 0xb39e // skein1024-496
	// Skein1024_504 is a codec with tag "multihash".
	Skein1024_504 Codec = 0xb39f // skein1024-504
	// Skein1024_512 is a codec with tag "multihash".
	Skein1024_512 Codec = 0xb3a0 // skein1024-512
	// Skein1024_520 is a codec with tag "multihash".
	Skein1024_520 Codec = 0xb3a1 // skein1024-520
	// Skein1024_528 is a codec with tag "multihash".
	Skein1024_528 Codec = 0xb3a2 // skein1024-528
	// Skein1024_536 is a codec with tag "multihash".
	Skein1024_536 Codec = 0xb3a3 // skein1024-536
	// Skein1024_544 is a codec with tag "multihash".
	Skein1024_544 Codec = 0xb3a4 // skein1024-544
	// Skein1024_552 is a codec with tag "multihash".
	Skein1024_552 Codec = 0xb3a5 // skein1024-552
	// Skein1024_560 is a codec with tag "multihash".
	Skein1024_560 Codec = 0xb3a6 // skein1024-560
	// Skein1024_568 is a codec with tag "multihash".
	Skein1024_568 Codec = 0xb3a7 // skein1024-568
	// Skein1024_576 is a codec with tag "multihash".
	Skein1024_576 Codec = 0xb3a8 // skein1024-576
	// Skein1024_584 is a codec with tag "multihash".
	Skein1024_584 Codec = 0xb3a9 // skein1024-584
	// Skein1024_592 is a codec with tag "multihash".
	Skein1024_592 Codec = 0xb3aa // skein1024-592
	// Skein1024_600 is a codec with tag "multihash".
	Skein1024_600 Codec = 0xb3ab // skein1024-600
	// Skein1024_608 is a codec with tag "multihash".
	Skein1024_608 Codec = 0xb3ac // skein1024-608
	// Skein1024_616 is a codec with tag "multihash".
	Skein1024_616 Codec = 0xb3ad // skein1024-616
	// Skein1024_624 is a codec with tag "multihash".
	Skein1024_624 Codec = 0xb3ae // skein1024-624
	// Skein1024_632 is a codec with tag "multihash".
	Skein1024_632 Codec = 0xb3af // skein1024-632
	// Skein1024_640 is a codec with tag "multihash".
	Skein1024_640 Codec = 0xb3b0 // skein1024-640
	// Skein1024_648 is a codec with tag "multihash".
	Skein1024_648 Codec = 0xb3b1 // skein1024-648
	// Skein1024_656 is a codec with tag "multihash".
	Skein1024_656 Codec = 0xb3b2 // skein1024-656
	// Skein1024_664 is a codec with tag "multihash".
	Skein1024_664 Codec = 0xb3b3 // skein1024-664
	// Skein1024_672 is a codec with tag "multihash".
	Skein1024_672 Codec = 0xb3b4 // skein1024-672
	// Skein1024_680 is a codec with tag "multihash".
	Skein1024_680 Codec = 0xb3b5 // skein1024-680
	// Skein1024_688 is a codec with tag "multihash".
	Skein1024_688 Codec = 0xb3b6 // skein1024-688
	// Skein1024_696 is a codec with tag "multihash".
	Skein1024_696 Codec = 0xb3b7 // skein1024-696
	// Skein1024_704 is a codec with tag "multihash".
	Skein1024_704 Codec = 0xb3b8 // skein1024-704
	// Skein1024_712 is a codec with tag "multihash".
	Skein1024_712 Codec = 0xb3b9 // skein1024-712
	// Skein1024_720 is a codec with tag "multihash".
	Skein1024_720 Codec = 0xb3ba // skein1024-720
	// Skein1024_728 is a codec with tag "multihash".
	Skein1024_728 Codec = 0xb3bb // skein1024-728
	// Skein1024_736 is a codec with tag "multihash".
	Skein1024_736 Codec = 0xb3bc // skein1024-736
	// Skein1024_744 is a codec with tag "multihash".
	Skein1024_744 Codec = 0xb3bd // skein1024-744
	// Skein1024_752 is a codec with tag "multihash".
	Skein1024_752 Codec = 0xb3be // skein1024-752
	// Skein1024_760 is a codec with tag "multihash".
	Skein1024_760 Codec = 0xb3bf // skein1024-760
	// Skein1024_768 is a codec with tag "multihash".
	Skein1024_768 Codec = 0xb3c0 // skein1024-768
	// Skein1024_776 is a codec with tag "multihash".
	Skein1024_776 Codec = 0xb3c1 // skein1024-776
	// Skein1024_784 is a codec with tag "multihash".
	Skein1024_784 Codec = 0xb3c2 // skein1024-784
	// Skein1024_792 is a codec with tag "multihash".
	Skein1024_792 Codec = 0xb3c3 // skein1024-792
	// Skein1024_800 is a codec with tag "multihash".
	Skein1024_800 Codec = 0xb3c4 // skein1024-800
	// Skein1024_808 is a codec with tag "multihash".
	Skein1024_808 Codec = 0xb3c5 // skein1024-808
	// Skein1024_816 is a codec with tag "multihash".
	Skein1024_816 Codec = 0xb3c6 // skein1024-816
	// Skein1024_824 is a codec with tag "multihash".
	Skein1024_824 Codec = 0xb3c7 // skein1024-824
	// Skein1024_832 is a codec with tag "multihash".
	Skein1024_832 Codec = 0xb3c8 // skein1024-832
	// Skein1024_840 is a codec with tag "multihash".
	Skein1024_840 Codec = 0xb3c9 // skein1024-840
	// Skein1024_848 is a codec with tag "multihash".
	Skein1024_848 Codec = 0xb3ca // skein1024-848
	// Skein1024_856 is a codec with tag "multihash".
	Skein1024_856 Codec = 0xb3cb // skein1024-856
	// Skein1024_864 is a codec with tag "multihash".
	Skein1024_864 Codec = 0xb3cc // skein1024-864
	// Skein1024_872 is a codec with tag "multihash".
	Skein1024_872 Codec = 0xb3cd // skein1024-872
	// Skein1024_880 is a codec with tag "multihash".
	Skein1024_880 Codec = 0xb3ce // skein1024-880
	// Skein1024_888 is a codec with tag "multihash".
	Skein1024_888 Codec = 0xb3cf // skein1024-888
	// Skein1024_896 is a codec with tag "multihash".
	Skein1024_896 Codec = 0xb3d0 // skein1024-896
	// Skein1024_904 is a codec with tag "multihash".
	Skein1024_904 Codec = 0xb3d1 // skein1024-904
	// Skein1024_912 is a codec with tag "multihash".
	Skein1024_912 Codec = 0xb3d2 // skein1024-912
	// Skein1024_920 is a codec with tag "multihash".
	Skein1024_920 Codec = 0xb3d3 // skein1024-920
	// Skein1024_928 is a codec with tag "multihash".
	Skein1024_928 Codec = 0xb3d4 // skein1024-928
	// Skein1024_936 is a codec with tag "multihash".
	Skein1024_936 Codec = 0xb3d5 // skein1024-936
	// Skein1024_944 is a codec with tag "multihash".
	Skein1024_944 Codec = 0xb3d6 // skein1024-944
	// Skein1024_952 is a codec with tag "multihash".
	Skein1024_952 Codec = 0xb3d7 // skein1024-952
	// Skein1024_960 is a codec with tag "multihash".
	Skein1024_960 Codec = 0xb3d8 // skein1024-960
	// Skein1024_968 is a codec with tag "multihash".
	Skein1024_968 Codec = 0xb3d9 // skein1024-968
	// Skein1024_976 is a codec with tag "multihash".
	Skein1024_976 Codec = 0xb3da // skein1024-976
	// Skein1024_984 is a codec with tag "multihash".
	Skein1024_984 Codec = 0xb3db // skein1024-984
	// Skein1024_992 is a codec with tag "multihash".
	Skein1024_992 Codec = 0xb3dc // skein1024-992
	// Skein1024_1000 is a codec with tag "multihash".
	Skein1024_1000 Codec = 0xb3dd // skein1024-1000
	// Skein1024_1008 is a codec with tag "multihash".
	Skein1024_1008 Codec = 0xb3de // skein1024-1008
	// Skein1024_1016 is a codec with tag "multihash".
	Skein1024_1016 Codec = 0xb3df // skein1024-1016
	// Skein1024_1024 is a codec with tag "multihash".
	Skein1024_1024 Codec = 0xb3e0 // skein1024-1024
	// Poseidon_Bls12_381_A2_Fc1 is a codec with tag "multihash" and described by: Poseidon using BLS12-381 and arity of 2 with Filecoin parameters.
	Poseidon_Bls12_381_A2_Fc1 Codec = 0xb401 // poseidon-bls12_381-a2-fc1
	// Poseidon_Bls12_381_A2_Fc1_Sc is a codec with tag "multihash" and described by: Poseidon using BLS12-381 and arity of 2 with Filecoin parameters - high-security variant.
	Poseidon_Bls12_381_A2_Fc1_Sc Codec = 0xb402 // poseidon-bls12_381-a2-fc1-sc
	// Zeroxcert_Imprint_256 is a codec with tag "zeroxcert" and described by: 0xcert Asset Imprint (root hash).
	Zeroxcert_Imprint_256 Codec = 0xce11 // zeroxcert-imprint-256
	// Fil_Commitment_Unsealed is a codec with tag "filecoin" and described by: Filecoin piece or sector data commitment merkle node/root (CommP & CommD).
	Fil_Commitment_Unsealed Codec = 0xf101 // fil-commitment-unsealed
	// Fil_Commitment_Sealed is a codec with tag "filecoin" and described by: Filecoin sector data commitment merkle node/root - sealed and replicated (CommR).
	Fil_Commitment_Sealed Codec = 0xf102 // fil-commitment-sealed
	// Holochain_Adr_V0 is a codec with tag "holochain" and described by: Holochain v0 address    + 8 R-S (63 x Base-32).
	Holochain_Adr_V0 Codec = 0x807124 // holochain-adr-v0
	// Holochain_Adr_V1 is a codec with tag "holochain" and described by: Holochain v1 address    + 8 R-S (63 x Base-32).
	Holochain_Adr_V1 Codec = 0x817124 // holochain-adr-v1
	// Holochain_Key_V0 is a codec with tag "holochain" and described by: Holochain v0 public key + 8 R-S (63 x Base-32).
	Holochain_Key_V0 Codec = 0x947124 // holochain-key-v0
	// Holochain_Key_V1 is a codec with tag "holochain" and described by: Holochain v1 public key + 8 R-S (63 x Base-32).
	Holochain_Key_V1 Codec = 0x957124 // holochain-key-v1
	// Holochain_Sig_V0 is a codec with tag "holochain" and described by: Holochain v0 signature  + 8 R-S (63 x Base-32).
	Holochain_Sig_V0 Codec = 0xa27124 // holochain-sig-v0
	// Holochain_Sig_V1 is a codec with tag "holochain" and described by: Holochain v1 signature  + 8 R-S (63 x Base-32).
	Holochain_Sig_V1 Codec = 0xa37124 // holochain-sig-v1
)
